/**
 * Which GitHub repository is this build of the board from?
 *
 * The update check and the installer both download from a release, so both
 * need to know whose releases to look at. Hard-coding that is wrong the moment
 * the code lives anywhere other than where it was written: this project is a
 * fork, and if these changes land upstream a build made from the upstream tree
 * would still fetch the fork's releases and install the fork's binaries over
 * whatever the user actually had.
 *
 * So it is resolved from the checkout that produced the build, in this order:
 *
 *   1. FRBOARD_REPO -- an explicit override, for builds made somewhere the
 *      other two answers would be wrong (CI on a mirror, a test release)
 *   2. the origin remote -- correct by construction. Whoever clones and builds
 *      gets their own repository without editing anything, which is the whole
 *      point
 *   3. package.json "repository" -- for a source archive, which has no git
 *      metadata at all
 *
 * Resolution happens at build time, never at runtime: a shipped exe is not in
 * a checkout and has no git to ask.
 */

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

/** "owner/name" out of any of the URL forms git hands back. */
function parse(url) {
  const match = url.trim().match(/github\.com[:/]+([^/]+)\/(.+?)(?:\.git)?\/?$/i);
  return match ? `${match[1]}/${match[2]}` : null;
}

function fromGit() {
  try {
    const url = execFileSync('git', ['config', '--get', 'remote.origin.url'], {
      cwd: root,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    });
    return parse(url);
  } catch {
    // No git, no remote, or not a checkout. All expected.
    return null;
  }
}

function fromManifest() {
  try {
    const manifest = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
    const url = manifest.repository?.url ?? manifest.repository;
    return typeof url === 'string' ? parse(url) : null;
  } catch {
    return null;
  }
}

export function resolveRepo() {
  return (
    process.env.FRBOARD_REPO ||
    fromGit() ||
    fromManifest() ||
    // Only reachable if the manifest lost its repository field too. Points at
    // the canonical project rather than any fork: a build that cannot say
    // where it came from should not claim to be somebody's fork.
    'KillDave/FuelRats_Dispatch_Message_Board'
  );
}

/**
 * Hand the same answer to the Python side.
 *
 * The installer ships as a frozen exe with no checkout to consult, so the value
 * has to be baked in before PyInstaller runs. installer.py imports this module
 * if it is there and falls back to asking git itself when it is not, which is
 * the case when it is run straight from source.
 */
function emit() {
  const repo = resolveRepo();
  const target = join(here, 'python', '_repo.py');
  writeFileSync(
    target,
    '# Generated by scripts/repo.mjs at build time -- do not edit, do not commit.\n' +
      `REPO = ${JSON.stringify(repo)}\n`,
    'utf8',
  );
  console.log(`repo: ${repo} -> ${target}`);
}

if (process.argv[2] === '--emit') emit();
